package org.deegraph.query;

public enum QueryExceptionCode {
    MISSING_TO_PARAMETER,
    MISSING_SUBJECT,
    INVALID_CONTROL_WORD,
    KEYS_DO_NOT_MAP_TO_VALUES, SCHEMAS_DO_NOT_MAP_TO_VALUES, DUPLICATE_PROPERTY_NAME,
    INVALID_COMBINATION
}
